
#ifndef __RESOURCES_H__
#define __RESOURCES_H__

#define SUIT_NOT_FOLLOWING_MASTER 1
#define CARD_NOT_RECOGNIZED 2
#define FIRST_MOVE 0
#define VALID_MOVE 0
#define PlayerId int
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define CARD_WIDTH 75
#define CARD_HEIGHT 107
#define SPACE_BETWEEN_CARDS_X 10
#define SPACE_BETWEEN_CARDS_Y 30
#define S_CARD_Y 480
#define N_CARD_Y 13
#define N_STATUS_POSITION_Y 130
#define S_STATUS_POSITION_Y 460
#define TIME_BETWEEN_ROUNDS 1.0




#endif
